services:
  frontend:
    image: node:22-alpine
    build:
      context: ./frontend
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    image: node:22-alpine
    build:
      context: ./backend
    command: npm run watch
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    working_dir: /app
    environment:
      - NODE_ENV=development

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
